services:
  eureka-server:
    image: samuelmlee/capitalcompass-eureka:v0.1
    ports:
      - "8010:8010"
  users:
    depends_on:
      - eureka-server
    image: samuelmlee/capitalcompass-users:v0.1
    volumes:
      - C:/Users/sam_m/.aws:/home/cnb/.aws:ro
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  stocks:
    depends_on:
      - eureka-server
    image: samuelmlee/capitalcompass-stocks:v0.1
    volumes:
      - C:/Users/sam_m/.aws:/home/cnb/.aws:ro
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  gateway:
    depends_on:
      - eureka-server
    image: samuelmlee/capitalcompass-gateway:v0.1
    volumes:
      - C:/Users/sam_m/.aws:/home/cnb/.aws:ro
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

