services:
  eureka-server:
    image: samuelmlee/capitalcompass-eureka:v0.1
    ports:
      - "8010:8010"
  users:
    image: samuelmlee/capitalcompass-users:v0.1
    volumes:
      - C:/Users/sam_m/.aws:/home/cnb/.aws:ro
    ports:
      - "8085:8085"
  stocks:
    image: samuelmlee/capitalcompass-stocks:v0.1
    volumes:
      - C:/Users/sam_m/.aws:/home/cnb/.aws:ro
    ports:
      - "8083:8083"
  gateway:
    image: samuelmlee/capitalcompass-gateway:v0.1
    volumes:
      - C:/Users/sam_m/.aws:/home/cnb/.aws:ro
    ports:
      - "8082:8082"

