server:
  port: 8082

webapp:
  url: ${WEBAPP_URL}
auth:
  issuer: https://${OKTA_DOMAIN}/
  client-id: ${OKTA_CLIENT_ID}

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s
    #    gateway:
    #      discovery:
    #        locator:
    #          enabled: true
    routes:
      - id: users-status
        uri: lb://users
        predicates:
          - Path=/users/status
          - Method=GET
        filters:
          - RemoveRequestHeader=Cookie

  session:
    store-type: redis
    timeout: 10m
    redis:
      namespace: capitalcompass:gateway
#  redis:
#    connect-timeout: 2s
#    host: localhost
#    port: 6379
#    timeout: 1s



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    root: DEBUG

# Okta Client
okta:
  oauth2:
    issuer: ${auth.issuer}
    client-id: ${auth.client-id}
    client-secret: ${OKTA_CLIENT_SECRET}
