server:
  port: 8082

webapp:
  url: ${WEBAPP_URL}

services:
  users:
    url: "http://users"
  stocks:
    url: "http://stocks"

spring:
  application:
    name: api-gateway
  profiles:
    active: deploy
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: capital-compass-gateway-client
            client-secret: ${keycloak.gateway.secret}
            authorization-grant-type: authorization_code
            scope: openid, roles
        provider:
          keycloak:
            issuer-uri: https://auth.capitalcompass.org:8443/realms/capitalcompass
  cloud:
    gateway:
      default-filters:
        - SaveSession
        - TokenRelay
      #      httpclient:
      #        connect-timeout: 2000
      #        response-timeout: 5s
      #      discovery:
      #        locator:
      #          enabled: true
      routes:
        - id: users-create-watchlist
          uri: lb://users
          predicates:
            - Path=/v1/users/watchlists
            - Method=POST
        - id: users-update-watchlist
          uri: lb://users
          predicates:
            - Path=/v1/users/watchlists
            - Method=PUT
        - id: users-delete-watchlist
          uri: lb://users
          predicates:
            - Path=/v1/users/watchlists/{watchlistId}
            - Method=DELETE
        - id: stocks-tickers
          uri: lb://stocks
          predicates:
            - Path=/v1/stocks/reference/tickers
            - Method=GET
        - id: stocks-tickers-with-cursor
          uri: lb://stocks
          predicates:
            - Path=/v1/stocks/reference/tickers/cursor/{cursor}
            - Method=GET
        - id: stocks-tickers-types
          uri: lb://stocks
          predicates:
            - Path=/v1/stocks/reference/tickers/types
            - Method=GET
        - id: stocks-tickers-details
          uri: lb://stocks
          predicates:
            - Path=/v1/stocks/reference/tickers/details/{ticker}
            - Method=GET

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info

    #  session:
    #    store-type: redis
    #    timeout: 10m
    #    redis:
    #      namespace: capitalcompass:gateway
    #  redis:
    #    connect-timeout: 2s
    #    host: localhost
    #    port: 6379
    #    timeout: 1s



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  #logging:
  #  level:
  #    org.springframework.security: TRACE
#    root: DEBUG


